config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session
  resources :goals, only: [:new, :create, :index, :show]
  resources :user_comments, only: [:new,:create]
  resources :goal_comments, only: [:new,:create]

  root to: "sessions#new"
end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  body       :string           not null
#  user_id    :integer          not null
#  completed  :boolean          default(FALSE)
#  public     :boolean          default(TRUE)
#  goal_date  :date             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Goal < ActiveRecord::Base
  validates :title, :body, :user_id, :goal_date, presence: true

  belongs_to :user

  has_many :comments, class_name: "GoalComment"
end

app/models/goal_comment.rb
# == Schema Information
#
# Table name: goal_comments
#
#  id         :integer          not null, primary key
#  body       :string           not null
#  author_id  :integer          not null
#  goal_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class GoalComment < ActiveRecord::Base
  validates :body, :author_id, :goal_id, presence: true

  belongs_to :author,
    foreign_key: :author_id,
    class_name: "User"

  belongs_to :goal
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_reader :password

  validates :username, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token

  has_many :goals

  has_many :goal_comments,
    through: :goals,
    source: :comments

  has_many :comments_on_users,
    foreign_key: :author_id,
    class_name: "UserComment"

  has_many :comments_on_goals,
    foreign_key: :author_id,
    class_name: "GoalComment"

  has_many :comments_on_self,
    foreign_key: :commentee_id,
    class_name: "UserComment"

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    user && user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/models/user_comment.rb
# == Schema Information
#
# Table name: user_comments
#
#  id           :integer          not null, primary key
#  body         :string           not null
#  author_id    :integer          not null
#  commentee_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class UserComment < ActiveRecord::Base
  validates :body, :author_id, :commentee_id, presence: true

  belongs_to :author,
    foreign_key: :author_id,
    class_name: "User"

  belongs_to :commentee,
    foreign_key: :commentee_id,
    class_name: "User"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login(user)
    session[:session_token] = user.session_token
  end

  def logout
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def check_signed_in
    redirect_to new_session_url unless current_user
  end

  def own_or_public_goal
    goal = Goal.find(params[:id])
    unless (current_user.id == goal.user_id) || (goal.public == true)
      redirect_to goals_url
    end
  end
end

app/controllers/goal_comments_controller.rb
class GoalCommentsController < ApplicationController
  def new
  end

  def create
    @comment = GoalComment.new(comment_params)
    @comment.author_id = current_user.id

    if @comment.save
      redirect_to goal_url(@comment.goal_id)
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to goal_url(@comment.goal_id)
    end
  end

  def comment_params
    params.require(:goal_comment).permit(:body, :goal_id)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :check_signed_in
  before_action :own_or_public_goal, only: [:show]

  def index
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id

    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  protected
  def goal_params
    params.require(:goal).permit(:title, :body, :goal_date, :public)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user
      login(user)
      redirect_to goals_url
    else
      flash.now[:errors] = ["Invalid credentials"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

app/controllers/user_comments_controller.rb
class UserCommentsController < ApplicationController
  def new
  end

  def create
    @comment = UserComment.new(comment_params)
    @comment.author_id = current_user.id

    if @comment.save
      redirect_to user_url(@comment.commentee_id)
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to user_url(@comment.commentee_id)
    end
  end

  private
  def comment_params
    params.require(:user_comment).permit(:body, :commentee_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to goals_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  protected
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goal_comments_helper.rb
module GoalCommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_comments_helper.rb
module UserCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/index.html.erb
<h2>All Public Goals</h2>
  <ul>
    <% Goal.all.each do |goal| %>
      <% if !!goal.public || goal.user_id == current_user.id %>
        <li><%= link_to goal.title, goal_url(goal) %>,
            <%= goal.user.username %></li>
      <% end %>
    <% end %>
  </ul>

  <%= link_to "Create New Goal", new_goal_url %>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<form action="<%= goals_url %>" method="post">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="Title">Title</label>
  <input type="text" id="Title" name="goal[title]">
  <br>

  <label for="Body">Body</label>
  <textarea name="goal[body]"
            id="Body"
            rows="8"
            cols="40"></textarea>
  <br>

  <label for="Goal_Date">Goal Date</label>
  <input type="date"
         name="goal[goal_date]"
         value="2016-01-01"
         id="Goal_Date">
  <br>

  <label>Public?</label>
  <input type="radio" name="goal[public]" value="true" id="public_true" checked>True
  <input type="radio" name="goal[public]" value="false" id="public_false">False
  <br>

  <input type="submit" value="Create Goal">
</form>

app/views/goals/show.html.erb
<h1>Here's your goal!</h1>

<p>
  <%= @goal.title %> :
  <%= @goal.body %>
</p>

<ul>
  <% @goal.comments.each do |comment| %>
    <li><%= comment.body %></li>
  <% end %>
</ul>

<form action="<%= goal_comments_url %>" method="post">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="add_comment">Add Comment : </label>
  <br>
    <textarea name="goal_comment[body]"
              rows="8"
              cols="40"
              id="add_comment"></textarea>
  <br>

  <input type="hidden"
         name="goal_comment[goal_id]"
         value="<%= @goal.id %>">

  <input type="submit" value="Add Comment">
</form>
<br>

<%= link_to "Back to Goals", goals_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Motivator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  <%= current_user.username %>
  <%= button_to "Sign Out", session_url, method: :delete %>
<% else %>
  <%= link_to "Sign In", new_session_url %>
  <%= link_to "Create User", new_user_url %>
<% end %>

<ul>
<% if flash.now[:errors] %>
  <% flash.now[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
<% end %>
</ul>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="Username">Username</label>
    <input type="text" name="user[username]" id="Username">
  <br>

  <label for="Password">Password</label>
    <input type="password" name="user[password]" id="Password">
  <br><br>

  <input type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<ul>
  <% @user.goals.each do |goal| %>
    <li><%= goal.title %></li>
  <% end %>
</ul>

<ul>
  <% @user.comments_on_self.each do |comment| %>
    <li><%= comment.body %></li>
  <% end %>
</ul>

<form  action="<%= user_comments_url %>" method="post">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

   <label for="add_comment">Add Comment : </label>
   <br>
     <textarea name="user_comment[body]"
               rows="8"
               cols="40"
               id="add_comment"></textarea>
   <br>

   <input type="hidden"
          name="user_comment[commentee_id]"
          value="<%= @user.id %>">

   <input type="submit" value="Add Comment">
 </form>
 <br>